<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\buttons.jpg" />
    <None Remove="assets\LogIn_Icon.png" />
    <None Remove="Custom-Icon-Design-Mono-General-4-Filter.512.png" />
    <None Remove="fonts\Goudy Heavyface Std Regular\Goudy Heavyface Std Regular.otf" />
    <None Remove="icon_itspot.png" />
    <None Remove="landscape.png" />
    <None Remove="lupe.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GMap.NET.Core" Version="2.1.7" />
    <PackageReference Include="GMap.NET.WinPresentation" Version="2.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\buttons.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\Custom-Icon-Design-Mono-General-4-Filter.512.png" />
    <Resource Include="assets\LogIn_Icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="fonts\Goudy Heavyface Std Regular\Goudy Heavyface Std Regular.otf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\icon_itspot.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\landscape.png" />
    <Resource Include="assets\lupe.png" />
  </ItemGroup>

</Project>
